### ISSUE TITLE
Notes?

### ISSUE THREAD

**Issue by ultimateshadsform** [anjomro/kobra-unleashed#2]
Just wondering.

Wouldn't it be better to just use a hostname redirect in /etc/hosts for mqtt-universe.anycubic.com instead of patching the binary?

**Comment by anjomro** [comment]
Hej! 
Yeah, that would be of course less invasive and therefore much better. I tried that during development, however I think it didn't work, if I remember correctly the hosts-file was ignored, at least for the mqtt hostnames. Instead there were calls to Google DNS / 8.8.8.8, possibly hardcoded? 

However I tested lots of stuff in a short time and it could be that I made some mistake that prevented it from working. I will test it again and report the results. Have you tried using the /etc/hosts on the Kobra?

I've read that you managed to create custom `.swu` updates and have some group for technical discussions for reverse engineering the Kobra. I'd be delighted to join you.

**Comment by ultimateshadsform** [comment]
What's your telegram name? I'll add you to the group.

**Comment by anjomro** [comment]
Let's say I'm not very creative at choosing usernames ;)

**Comment by ultimateshadsform** [comment]
anjomro then I assume?
