### ISSUE TITLE
It won't run on arm64 V8

### ISSUE THREAD

**Issue by logiota** [anjomro/kobra-unleashed#4]
Thank you so much for this great work!

~/dev/kobra-unleashed master* ❯ docker-compose up -d
[+] Running 1/2
 ⠸ kobra-unleashed Pulling                                                                                              5.3s 
 ✘ eclipse-mosquitto Error                                                                                              5.3s 
no matching manifest for linux/arm64/v8 in the manifest list entries

eclipse-mosquitto clearly supports it
https://hub.docker.com/_/eclipse-mosquitto

I am not a big Docker fan 😬
Any chance you could point me in the direction of how to run it natively and locally?

**Comment by anjomro** [comment]
Hey!
Currently the prebuilt docker image for kobra unleashed is only supporting amd64. I just pushed some changes, that should automatically fall back to building the image locally, that should work for other architectures such as arm64 as well, however i haven't tested that. I suppose the error is thrown for the kobra-unleashed image and not the mosquitto image.

The application should be quite easy to run yourself as well, however it needs some manual configuration.

1. For running the kobra-unleashed backend you need Python 3.10 or above with the package management tool pipenv. You should be able to install all dependencies (automatically inside a virtualenv) by running `pipenv install` in the project root and running `pipenv shell` to get a shell within this virtualenv. 
2. Please consult the [main.py](https://github.com/anjomro/kobra-unleashed/blob/1ca19151f2bf15439651c189f74d77f61eab3a0b/main.py) on the configuration options. You need to set at least the following environment variables: 
    - ROOT_URL (URL under which the web application can be reached)
    - MQTT_HOST (Host where your mosquitto server runs, probably localhost if running baremetal on the same device)
    - MQTT_CA (Path to the generated ./certs/ca.pem )
    - MQTT_CERT (Path to the generated ./certs/client.pem)
    - MQTT_KEY (Path to the generated ./certs/client.key)
3. Run the mosquitto server with enabled tls on port 8883, use the `msoquito.conf` in the repo for that. Please make sure to change the paths of the certs to your kobra-unleashed/certs directory.
4. You need to compile the Vue frontend using nodejs. Please consult the [Dockerfile](https://github.com/anjomro/kobra-unleashed/blob/master/Dockerfile) on the necessary commands.

As you can see it's quite some work without Docker. Feel free to try if you feel more comfortable with it, however from my perspective it's much easier to use `docker compose`.
